@startuml

title "Sistema de Portfólio"
' Define o ator "Administrador" à esquerda
left to right direction
actor "Administrador" as admin

' Define o ator "Visitante" à direita
actor "Visitante" as visitor

' Define o retângulo que representa o sistema
rectangle {
  ' Casos de uso do Administrador
  usecase "Autenticar no Sistema" as UC1
  usecase "Gerenciar Projetos" as UC2

  ' Casos de uso do Visitante
  usecase "Listar Projetos" as UC3
  usecase "Visualizar Projeto" as UC4
}

' Ligações dos atores aos casos de uso
admin -- UC1
admin -- UC2

visitor -- UC3
visitor -- UC4

' Detalhando o caso de uso "Gerenciar Projetos" com include
' "include" significa que um caso de uso sempre inclui o outro
UC2 .> (Adicionar Projeto) : <<include>>
UC2 .> (Editar Projeto) : <<include>>
UC2 .> (Excluir Projeto) : <<include>>

@enduml