' UML - Diagrama de Casos de Uso
@startuml CASO_DE_USO

' Define o título do diagrama
title Sistema de Blog

' Define o ator "Autor" à esquerda
left to right direction
actor "Autor" as autor

' Define o ator "Leitor" à direita
actor "Leitor" as leitor

' Define o retângulo que representa o sistema
rectangle {
  ' Casos de uso do Autor
  usecase "Autenticar no Sistema" as UC1
  usecase "Gerenciar Posts" as UC2
  usecase "Gerenciar Categorias" as UC3
  usecase "Moderar Comentários" as UC4

  ' Casos de uso do Leitor
  usecase "Listar Posts" as UC5
  usecase "Visualizar Post" as UC6
  usecase "Adicionar Comentário" as UC7
}

' Ligações dos atores aos casos de uso
autor -- UC1
autor -- UC2
autor -- UC3
autor -- UC4

leitor -- UC5
leitor -- UC6
leitor -- UC7

' Detalhando o caso de uso "Gerenciar Posts" com include
' "include" significa que um caso de uso sempre inclui o outro
UC2 .> (Criar Post) : <<include>>
UC2 .> (Editar Post) : <<include>>
UC2 .> (Publicar Post) : <<include>>

@enduml

' para visualizar o diagrama, use alt + D no VS Code com a extensão PlantUML
